// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlyq9Qf_DCkJAT4I21SPCHNPGvEf2LtS0',
    appId: '1:312410734673:web:d23c0b94820df1f3fcb870',
    messagingSenderId: '312410734673',
    projectId: 'pakdoekang',
    authDomain: 'pakdoekang.firebaseapp.com',
    storageBucket: 'pakdoekang.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATBKxqOWwF2hka1Pb7eIQ9X4DmAtaNesM',
    appId: '1:312410734673:android:55791ade5e001cfffcb870',
    messagingSenderId: '312410734673',
    projectId: 'pakdoekang',
    storageBucket: 'pakdoekang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAda-8zYzGEuhKG_o5YhFPUqx5wM1H1LWU',
    appId: '1:312410734673:ios:77ab5220c2e3b926fcb870',
    messagingSenderId: '312410734673',
    projectId: 'pakdoekang',
    storageBucket: 'pakdoekang.appspot.com',
    iosBundleId: 'com.example.pakdoekang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAda-8zYzGEuhKG_o5YhFPUqx5wM1H1LWU',
    appId: '1:312410734673:ios:77ab5220c2e3b926fcb870',
    messagingSenderId: '312410734673',
    projectId: 'pakdoekang',
    storageBucket: 'pakdoekang.appspot.com',
    iosBundleId: 'com.example.pakdoekang',
  );
}
